name: Hello world
run-name: ${{ github.actor }} says hello!

on:
  pull_request:
    branches:
      - main

env:
  GREETEE: 'Claudia'
  GREETER: ${{ github.actor}}

jobs:
  tests:
    name: ğŸ§ª Tests
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: â”  Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ”’ Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: ğŸ“¥ Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --legacy-peer-deps

      - name: ğŸ§ª Test
        run: npm test

  lint:
    name: ğŸ”¬ Lint
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: â”  Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ”’ Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: ğŸ“¥ Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --legacy-peer-deps

      - name: ğŸ”¬ Lint
        run: npm run lint

  build:
    name: ğŸ³ build
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: â”  Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ”’ Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: ğŸ“¥ Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --legacy-peer-deps

      - name: ğŸ³ Build
        run: npm run build
